### ISSUE TITLE
Cannot run the project

### ISSUE THREAD

**Issue by ghost** [clwillingham/LEAP-OSXGestureController#1] opened 2013-02-11 11:27 UTC
Hey,
i'm very interested in your project but when i try to compile it i get the following error:

dyld: Library not loaded: @loader_path/libLeap.dylib
  Referenced from: /Users/joyrex/Library/Developer/Xcode/DerivedData/OSXGestureControl-dyfbkvnsjsaqhtapkmezultumgwf/Build/Products/Debug/OSXGestureControl.app/Contents/MacOS/OSXGestureControl
  Reason: image not found

I tried to link the frameworks and moved stuff around so every reference is correct!

**Comment by clwillingham** [comment] 2013-02-11 17:55
That error is caused by an environment variable (someday i will actually
get proper compile instructions on the readme)

to fix that problem, go to Product -> Scheme -> Edit Scheme -> Run
OSXGestureControl (on the sidebar). from there edit the DYLD_LIBRARY_PATH
which is currently set to the lib directory for the LEAP_SDK/lib folder on
my computer, and change it to the LEAP_SDK/lib folder on your computer
wherever that is located. that should solve the problem.
if that does not solve the problem, let me know and hopefully we can figure
out what the problem is. i'd like to get this to compile into a single Osx
app that anyone can install, so if you have any ideas of how to do that.
feel free to clone it and make any changes you'd like, i will except pull
requests

Thanks,
Chris

**Comment by ghost** [comment] 2013-02-12 08:52
Thanks for your answer, i will try this and let you know!

**Comment by clwillingham** [comment] 2013-02-12 19:56
just merged your changes, once i can get someone else to compile and run from the repository, i'll close the issue, thanks

**Comment by ghost** [comment] 2013-02-12 20:00
Excellent, thank you very much!

PS. i tried to compile it in another machine and it seems fine but it's best to check if someone else is able to!

**Comment by clwillingham** [comment] 2013-02-12 21:39
works fine on another machine too, i'm closing it, Thanks

**Closed as completed by clwillingham** 2013-02-12 21:39 UTC

**Comment by ghost** [comment] 2013-02-12 21:47
awesome!

PS. do you mind if i play around with the project a bit? Your idea is very interesting and i'd like to put some work into it!

**Comment by clwillingham** [comment] 2013-02-12 22:37
Sure, go ahead! thats why i published it I'd love to see what else can be done with it. I made the project to get people thinking about other ways to use the leap motion. feel free to do whatever you want with the project.

**Comment by ghost** [comment] 2013-02-13 00:12
great, i will keep you updated then! :)
